version: 1.0.1.{build}
install:
  - ps: iwr https://get.dot.net/v1/dotnet-install.ps1 -outfile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300 -InstallDir $env:ProgramFiles/dotnet
branches:
  only:
    - master
    - appveyor
    - /^feature\/.*/
image:
  - Ubuntu
  - Visual Studio 2017
build_script:
  - ps: .\build.ps1 -IsOfficialBuild
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
os: Visual Studio 2017
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Packages
    type: NuGetPackages
deploy:
  - provider: NuGet
    name: myget
    artifact: Packages
    server: https://www.myget.org/F/natemcmaster/api/v2/package
    symbol_server: https://www.myget.org/F/natemcmaster/api/v2/package
    api_key:
      secure: KF1yGk4IHJyyfiHfFSCxJ+p5iZX+KPfCTnCihjD5iIZjasTS1lHeilpbaon4wvcM
  - provider: GitHub
    description: 'See https://github.com/natemcmaster/dotnet-serve/blob/master/CHANGELOG.md for details'
    auth_token:
      secure: 7gza5cyC0Fwp5LcFPz9dGMcHXP2jxbrnu7er9R/HkdvnhzGJVADvOtfYO7+Vow5p
    artifact: Packages
    draft: false
    prerelease: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only
